version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-world
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/docker_build.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/docker_stop.sh
      timeout: 300
      runas: root

