version: 0.0
os: linux
# files:
#   - source: /
#     destination: /aws-codepipeline
hooks:
  BeforeInstall:
    - location: scripts/docker_build.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/docker_stop.sh
      timeout: 300
      runas: root

